MAX_INPUT_LENGTH = 36

BACKGROUND_COLOR = '#63112e'

ADDITIONAL_BUTTONS_COLOR = '#f4c430'
DARK_ADDITIONAL_BUTTONS_COLOR = '#c9a021'

DECIMAL_COLOR = '#CBA98F'
DARK_DECIMAL_COLOR = '#ad8668'

ROMAN_COLOR = '#a0a0a0'
DARK_ROMAN_COLOR = '#666666'

ROMAN_NUMERAL_REGEX = /\A[MDCLXVI]+\z/
ARABIC_NUMERAL_REGEX = /\A\d+\z/

LABELS_FONT = TkFont.new(family: 'Century Gothic', size: 15)
BUTTON_FONT = TkFont.new(family: 'Century Gothic', size: 10)

WINDOW_WIDTH = 450
WINDOW_HEIGHT = 450